apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: colours
  name: colours
spec:
  replicas: 2
  selector:
    matchLabels:
      app: colours
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: colours
    spec:
      containers:
      - image: ghcr.io/gdwr/colours:master
        imagePullPolicy: ""
        name: colours
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 30
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: colours
spec:
  type: NodePort
  selector:
    app: colours
  ports:
  - name: colours
    protocol: TCP
    nodePort: 30080
    port: 80
    targetPort: 8080
